### ISSUE TITLE
Show Talk shares

### ISSUE THREAD

**Issue by sbe-arg** [Rello/sharereview#9]
I love this app for autiding purposes but find a bit confusing that it shows all the pictures/screenshots shared in talk conversations.

Talk shares are not public and cannot be deleted/invalidated either.

Whats the purpose on showing the talk shares at all? 
Maybe we could add a flag to ignore/hide certain paths?

![image](https://github.com/user-attachments/assets/c1d79695-bb74-431f-9f9f-6cd2040a998b)

**Comment by Rello** [comment]
interesting finding!
will check

**Comment by Rello** [comment]
Hi,
I think they are valid shares and should be displayed

with the next version, the table is optimized. I suggest to add these with a Talk-Type Logo plus the talk room they are shared with. what do you think?

Because at the end a public talk room with a shared file can also mean a risk of data loss.

<img width="1079" alt="Bildschirmfoto 2024-11-06 um 19 26 09" src="https://github.com/user-attachments/assets/9fc57a9e-68f6-4c59-8820-b587268068e8">

**Comment by sbe-arg** [comment]
Yeah nice

**Comment by Rello** [comment]
Hi,
the new version is out. can you let me know how it looks on your side?

**Comment by sbe-arg** [comment]
It broke the app actually. :facepalm: 

![image](https://github.com/user-attachments/assets/d17f40ab-5264-48fa-a783-93d989a6ee34)

![image](https://github.com/user-attachments/assets/f3d9de97-3433-4299-a81b-30271250b214)

**Comment by sbe-arg** [comment]
I have 2 almost identical nc instances. It broke on both.

**Comment by Rello** [comment]
1.3.1 is out. I appreciate your feedback here

**Comment by sbe-arg** [comment]
All sorted, thanks @Rello works great again.

**Comment by sbe-arg** [comment]
@Rello the only thing I noticed is that is you have no shares (like in a fresh server) it results in similar error but with argument 1 instead of 2.

Not that is a big issue but good to keep it in mind.

![image](https://github.com/user-attachments/assets/d57aee2a-d683-46c2-bf8a-1653e32c28a5)
